server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pfhello/microservicecloud-config.git #Github上面git仓库地址
 #访问http:config3344:3344/application-dev.yml,http:config3344:3344/application-test.yml
