server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul

eureka:
  client: #客户端注册进eureka服务内
    service-url:
     #defaultZone: http://127.0.0.1:7001/eureka 单机版
     #注册进eureka集群
     defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-zuul-9527 #服务别名
    prefer-ip-address: true    #访问路径可以显示ip

info:
   app.name: microservicecloud-dept
   company.name: cn.itcast.cloud
   build.artifactId: ${project.artifactId}
   build.version: ${project.version}
zuul:
  prefix: /cloud #前缀
  #ignored-services: microservicecloud-dept #忽略真实名称
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**






